name: CI/CD Pipeline

on:
  # Run tests on every pull request
  pull_request:
    branches: [ master, main ]
  
  # Deploy when merging to master
  push:
    branches: [ master, main ]
  
  # Allow manual deployment
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging

jobs:
  # Test job - runs on PRs and pushes
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run type check
      run: npm run type-check

    - name: Run linting
      run: npm run lint

    - name: Build application
      run: npm run build

  # Deploy job - only runs on master push or workflow dispatch
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Render
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}

    - name: Deployment Success Notification
      if: success()
      run: |
        echo "🚀 Deployment to Render completed successfully!"
        echo "Environment: ${{ github.event.inputs.environment || 'production' }}"
        
    - name: Deployment Failure Notification
      if: failure()
      run: |
        echo "❌ Deployment to Render failed!"
        echo "Please check the deployment logs for more details."
