name: Test Suite

on:
  # Run on every pull request
  pull_request:
    branches: [ master, main ]
  
  # Run on pushes to any branch (except master/main to avoid duplication)
  push:
    branches-ignore: [ master, main ]

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run type check
      run: npm run type-check

    - name: Run linting
      run: npm run lint

    - name: Check code formatting
      run: npm run format:check

    - name: Build application
      run: npm run build

    - name: Test build output
      run: |
        echo "Checking if build was successful..."
        if [ -d ".next" ]; then
          echo "✅ Build directory exists"
          ls -la .next/
        else
          echo "❌ Build directory not found"
          exit 1
        fi

  # Security and dependency check
  security:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run security audit
      run: npm audit --audit-level moderate

    - name: Check for outdated packages
      run: npm outdated || true
